### ISSUE TITLE
connection exception

### ISSUE THREAD

**Issue by aiwanwan** [chenyuntc/Simplified-FasterRCNN#211]
who can help me ? I really need help. I already opened visdom, but when I train, I meet these exception.
`(simp) E:\目标检测\simple-faster-rcnn-pytorch-master>python train.py train --env='fasterrcnn-caffe' --plot-every=100 --caffe-pretrain
======user config========
{'caffe_pretrain': True,
 'caffe_pretrain_path': 'E:/目标检测/simple-faster-rcnn-pytorch-master/checkpoints/vgg16-caffe.pth',
 'data': 'voc',
 'debug_file': '/tmp/debugf',
 'env': 'fasterrcnn-caffe',
 'epoch': 14,
 'load_path': None,
 'lr': 0.001,
 'lr_decay': 0.1,
 'max_size': 1000,
 'min_size': 600,
 'num_workers': 0,
 'plot_every': 100,
 'port': 8097,
 'pretrained_model': 'vgg16',
 'roi_sigma': 1.0,
 'rpn_sigma': 3.0,
 'test_num': 10000,
 'test_num_workers': 0,
 'use_adam': False,
 'use_chainer': False,
 'use_drop': False,
 'voc_data_dir': 'E:/目标检测/simple-faster-rcnn-pytorch-master/VOCdevkit/VOC2007/',
 'weight_decay': 0.0005}
==========end============
load data
model construct completed
Setting up a new session...
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Anaconda\envs\simp\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "D:\Anaconda\envs\simp\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "D:\Anaconda\envs\simp\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\simp\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "D:\Anaconda\envs\simp\lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "D:\Anaconda\envs\simp\lib\http\client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\Anaconda\envs\simp\lib\http\client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\Anaconda\envs\simp\lib\http\client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\Anaconda\envs\simp\lib\http\client.py", line 1032, in _send_output
    self.send(msg)
  File "D:\Anaconda\envs\simp\lib\http\client.py", line 972, in send
    self.connect()
  File "D:\Anaconda\envs\simp\lib\site-packages\urllib3\connection.py", line 181, in connect
    conn = self._new_conn()
  File "D:\Anaconda\envs\simp\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000023FF3EBA848>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\simp\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "D:\Anaconda\envs\simp\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "D:\Anaconda\envs\simp\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='ag.knew.be', port=8097): Max retries exceeded with url: /env/fasterrcnn-caffe (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023FF3EBA848>: F
ailed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\simp\lib\site-packages\visdom\__init__.py", line 711, in _send
    data=json.dumps(msg),
  File "D:\Anaconda\envs\simp\lib\site-packages\visdom\__init__.py", line 677, in _handle_post
    r = self.session.post(url, data=data)
  File "D:\Anaconda\envs\simp\lib\site-packages\requests\sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "D:\Anaconda\envs\simp\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Anaconda\envs\simp\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "D:\Anaconda\envs\simp\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='ag.knew.be', port=8097): Max retries exceeded with url: /env/fasterrcnn-caffe (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023FF3EBA848>
: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
Without the incoming socket you cannot receive events from the server or register event handlers to your Visdom client.
Setting up a new session...
Without the incoming socket you cannot receive events from the server or register event handlers to your Visdom client.
`

**Comment by QianLingjun** [comment]
sir ,are you address this problem? i find this problem too.Thinks

**Comment by aiwanwan** [comment]
no sorry

 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "QianLingjun"<notifications@github.com&gt;; 
发送时间: 2020年10月28日(星期三) 下午2:21
收件人: "chenyuntc/simple-faster-rcnn-pytorch"<simple-faster-rcnn-pytorch@noreply.github.com&gt;; 
抄送: "814286591"<814286591@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [chenyuntc/simple-faster-rcnn-pytorch] connection exception (#211)





 
sir ,are you address this problem? i find this problem too.Thinks

**Comment by SpeitzerPatrick** [comment]
i experience the same issues, i dont know why

**Comment by xiaoli-user** [comment]
me too

**Comment by kaushikb258** [comment]
Type the following command in another terminal when you train the model:

python -m visdom.server
