### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by xiaoli-user** [chenyuntc/Simplified-FasterRCNN#244]
I failed to run train.py.The error is that: 

Traceback (most recent call last):
  File "/root/anaconda3/envs/graph4nlp/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/root/anaconda3/envs/graph4nlp/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/root/anaconda3/envs/graph4nlp/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7faf57381390>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

**Comment by kaushikb258** [comment]
It's a visdom error. Type the following command in another terminal when you run train.py:

python -m visdom.server
