### ISSUE TITLE
why Missing key(s)& Unexpected key(s)

### ISSUE THREAD

**Issue by hischen** [chenyuntc/Simplified-FasterRCNN#95]
/home/simple-faster-rcnn-pytorch/model/utils/nms/non_maximum_suppression.py:12: UserWarning:
    the python code for non_maximum_suppression is about 2x slow
    It is strongly recommended to build cython code:
    `cd model/utils/nms/; python3 build.py build_ext --inplace
  `cd model/utils/nms/; python3 build.py build_ext --inplace''')
======user config========
{'caffe_pretrain': True,
 'caffe_pretrain_path': '/root/.torch/models/vgg16_caffe.pth',
 'data': 'voc',
 'debug_file': '/tmp/debugf',
 'env': 'fasterrcnn-caffe',
 'epoch': 14,
 'load_path': None,
 'lr': 0.001,
 'lr_decay': 0.1,
 'max_size': 1000,
 'min_size': 600,
 'num_workers': 8,
 'plot_every': 100,
 'port': 8097,
 'pretrained_model': 'vgg16',
 'roi_sigma': 1.0,
 'rpn_sigma': 3.0,
 'test_num': 600,
 'test_num_workers': 8,
 'use_adam': False,
 'use_chainer': False,
 'use_drop': False,
 'voc_data_dir': '/home/simple-faster-rcnn-pytorch/data/VOCdevkit/VOC2012/',
 'weight_decay': 0.0005}
==========end============
load data
Traceback (most recent call last):
  File "train.py", line 132, in <module>
    fire.Fire()
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "train.py", line 67, in train
    faster_rcnn = FasterRCNNVGG16()
  File "/home/simple-faster-rcnn-pytorch/model/faster_rcnn_vgg16.py", line 63, in __init__
    extractor, classifier = decom_vgg16()
  File "/home/simple-faster-rcnn-pytorch/model/faster_rcnn_vgg16.py", line 17, in decom_vgg16
    model.load_state_dict(t.load(opt.caffe_pretrain_path))
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for VGG:
        Missing key(s) in state_dict: "classifier.0.weight", "classifier.0.bias", "classifier.3.weight", "classifier.3.bias".
        Unexpected key(s) in state_dict: "classifier.1.weight", "classifier.1.bias", "classifier.4.weight", "classifier.4.bias".

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by GloriaZLQ** [comment]
have you solve this problem?

**Comment by gmt710** [comment]
@GloriaZLQ  I solved the problem by [this](thishttps://github.com/chenyuntc/simple-faster-rcnn-pytorch/issues/25#issuecomment-374199928).

**Comment by zou-longkun** [comment]
I met the same issue，have you solve this problem?

**Comment by gmt710** [comment]
@zou-longkun https://github.com/chenyuntc/simple-faster-rcnn-pytorch/issues/25#issuecomment-374462311.This might help you.
